#!/usr/bin/env bash

###### Variables ######
LABEL="${LABEL:- }"
LOCATION="${LOCATION:-}"
UNIT_SYSTEM="${UNIT_SYSTEM:-m}"  # "m" for metric, "u" for US, etc.
FONT="${FONT:-Monospace 10}"
ROFI_CONFIG_FILE="${ROFI_CONFIG_FILE:-/dev/null}"

# Use ANCHOR to control rofi's anchor directly:
ANCHOR="${ANCHOR:-southwest}"   # default to "southwest" if not set

###### Functions ######
print_weather_report() {
  if [[ -n "$LOCATION" ]]; then
    curl "https://wttr.in/${LOCATION}?${UNIT_SYSTEM}"
  else
    curl "https://wttr.in?${UNIT_SYSTEM}"
  fi
}

print_weather_line() {
  if [[ -n "$LOCATION" ]]; then
    curl -s "https://wttr.in/${LOCATION}?${UNIT_SYSTEM}&format=\"%C+%c+%t+(%f)+%w\"" | tr -d \"
  else
    curl -s "https://wttr.in?${UNIT_SYSTEM}&format=\"%C+%c+%t+(%f)+%w\"" | tr -d \"
  fi
}

###### Main body ######
case "$BLOCK_BUTTON" in
  1|2|3)
    weather_report=$(print_weather_report)

    # Use the user-defined $ANCHOR for rofi
    echo "$weather_report" \
      | rofi \
          -dmenu \
          -markup-rows \
          -font "$FONT" \
          -m -3 \
          -theme-str "window {width: 53%; anchor: $ANCHOR; location: northwest;}" \
          -theme-str "listview {lines: $(echo "$weather_report" | wc -l); scrollbar: false;}" \
          -theme "$ROFI_CONFIG_FILE" \
          -p "Detailed weather report"
esac

if [[ -n "$LABEL" ]]; then
  echo "$LABEL$(print_weather_line)"
else
  echo "$(print_weather_line)"
fi
