#!/usr/bin/env bash

###### Variables ######
LABEL="${LABEL:- }"
LOCATION="${LOCATION:-}"
UNIT_SYSTEM="${UNIT_SYSTEM:-m}"  # "m" = metric, "u" = US, etc.
FONT="${FONT:-Monospace 10}"
ROFI_CONFIG_FILE="${ROFI_CONFIG_FILE:-/dev/null}"
BAR_POSITION="${BAR_POSITION:-bottom}"

###### Functions ######
# print the full weather
print_weather_report() {
  # If LOCATION is empty, the script uses your IP-based location
  if [[ -n "$LOCATION" ]]; then
    curl "https://wttr.in/${LOCATION}?${UNIT_SYSTEM}"
  else
    curl "https://wttr.in?${UNIT_SYSTEM}"
  fi
}

# print the one-line weather
print_weather_line() {
  if [[ -n "$LOCATION" ]]; then
    curl -s "https://wttr.in/${LOCATION}?${UNIT_SYSTEM}&format=\"%C+%c+%t+(%f)+%w\"" \
      | tr -d \"
  else
    curl -s "https://wttr.in?${UNIT_SYSTEM}&format=\"%C+%c+%t+(%f)+%w\"" \
      | tr -d \"
  fi
}

###### Main body ######
case "$BLOCK_BUTTON" in
  1|2|3)
    weather_report=$(print_weather_report)

    if [[ $BAR_POSITION = "top" ]]; then
      anchor="northwest"
    else
      anchor="southwest"
    fi

    echo "$weather_report" \
      | rofi \
          -dmenu \
          -markup-rows \
          -font "$FONT" \
          -m -3 \
          -theme-str "window {width: 53%; anchor: $anchor; location: northwest;}" \
          -theme-str "listview {lines: $(echo "$weather_report" | wc -l); scrollbar: false;}" \
          -theme "$ROFI_CONFIG_FILE" \
          -p "Detailed weather report"
esac

if [[ -n "$LABEL" ]]; then
  echo "$LABEL$(print_weather_line)"
else
  echo "$(print_weather_line)"
fi
